[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs-20.x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[staticAssets]
".next/static" = "./.next/static"
"public" = "./public"
